inception/inception/urls.py
from django.contrib import admin
from django.urls import path , include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('subjects/',include('subjects.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

]

inception/subjects/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name="subjects"

urlpatterns =[
    path('',views.index , name="index"),
    path('<int:subject_id>',views.subject,name="subject"),
    path('<str:subject_id>/enroll' ,views.enroll,name="enroll"),
    path('<str:subject_id>/drop' ,views.drop,name="drop"),
    path('Course' ,views.Course,name="Course"),

    ]

inception/subjects/models.py
from django.db import models
from django.contrib.auth.models import User




class Subject(models.Model):

    class ans(models.TextChoices):
        free = "free"
        full = "full"

    subject_name = models.CharField(max_length=100)
    subject_code = models.CharField(max_length=10)
    semester = models.IntegerField(default=None, null=True)
    year = models.IntegerField(default=None, null=True)
    limited_seat = models.IntegerField(default=None, null=True)
    seat = models.IntegerField(default=None, null=True)
    studentInClass =models.ManyToManyField(User,blank=True,related_name="studentlist")

    status = models.CharField(
        max_length=4,
        choices=ans.choices,
        default=ans.free,
        )

    def __str__(self):
        return f"{self.subject_code} : {self.subject_name}"

inception/subjects/views.py
from django.shortcuts import render ,get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

from .models import Subject
from django.contrib.auth.models import User

def index (request):
    return render(request,"subjects/index.html",{
        "subjects": Subject.objects.all(),
        "user":request.user,
})

def subject (request,subject_id):
    subject = get_object_or_404(Subject,pk=subject_id)
    my =Subject.objects.filter(pk=subject_id)

    return render(request,"subjects/subject.html",{
        "subject": subject,"course": my,"user":request.user,
    })

def Course (request):
    my =request.user.studentlist.all()
    return render(request,"subjects/MyCourse.html",{

        "course": my,

    })



def enroll (request,subject_id):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    subject = get_object_or_404(Subject,pk=subject_id)


    me  = Subject.objects.filter(pk=subject_id)

    for x in me:
        print(request.user in x.studentInClass.all())

    if subject.limited_seat < 1:
            Subject.objects.filter(pk=subject_id).update(status="full")
    elif  request.user not in x.studentInClass.all():
            subject.studentInClass.add(request.user)
            Subject.objects.filter(pk=subject_id).update(seat=(subject.seat-1))


    return HttpResponseRedirect(reverse("subjects:subject",args=(subject_id,)))



def drop (request,subject_id):
    subject = get_object_or_404(Subject,pk=subject_id)
    me  = Subject.objects.filter(pk=subject_id)

    for x in me:
        print(request.user in x.studentInClass.all())


    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    if  subject.studentInClass.count()+subject.seat == subject.limited_seat:
        Subject.objects.filter(pk=subject_id).update(status="free")

    if request.user in x.studentInClass.all():
        print(request.user in x.studentInClass.all())
        subject.studentInClass.remove(request.user)
        Subject.objects.filter(pk=subject_id).update(seat=(subject.seat+1))



    return HttpResponseRedirect(reverse("subjects:subject",args=(subject_id,)))

inception/subjects/templates/subjects/MyCourse.html
{% extends "subjects/layout.html" %}


{% block body %}
    <nav>

    <label class="logo" ><a href="{% url 'subjects:index' %}">Subject</a></label>
    <ul>
    <li><a class="active" href="https://ide-6bd6267e6ac441ff8a573303d9997bd7-8080.cs50.ws/">HOME</a></li>

    <li><a href="{% url 'subjects:Course' %}">course</a></li>
    </ul>
    </nav>
    <br><br>
    <center><h2>COURSE</h2></center><br>
     <center><TABLE>
             <thead>
            <tr>
                <TH> Subject ID</TH>
                <TH> Subject Name</TH>
            </tr>
            </thead>


    {% for list_s in course %}
    <TR>
         <TD>{{list_s.subject_code}}</TD>
         <TD>{{ list_s.subject_name }}</TD>
         </TR>
    {% endfor %}
   </TABLE></center>


{% endblock %}

inception/subjects/templates/subjects/index.html
{% extends "subjects/layout.html" %}


{% block body %}
    <nav>

    <label class="logo" ><a href="{% url 'subjects:index' %}">Subject</a></label>
    <ul>
    <li><a class="active" href="https://ide-6bd6267e6ac441ff8a573303d9997bd7-8080.cs50.ws/">HOME</a></li>

    <li><a href="{% url 'subjects:Course' %}">course</a></li>
    </ul>
    </nav><br>

    <center><TABLE>

            <TR>
                <TH> Subject ID</TH>
                <TH> Subject Name</TH>
                <TH> Status </TH>
            </TR>

    {% for list_s in subjects %}
    <TR>
         <td><p><a href = "{% url 'subjects:subject' list_s.id %}" >
             <div>{{list_s.subject_code}}</div></a></td>
         <TD>{{list_s.subject_name}}</TD>
         <TD>{{ list_s.status }}</TD>
         </TR>
    {% endfor %}



    </TABLE></center>

{% endblock %}

inception/subjects/templates/subjects/layout.html
<!DOCTYPE html>
<html>
    <head>
        <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Ubuntu&display=swap');
            * {padding: 0;
            margin:0;
            text-decoration: none;
            list-style: none;
            box-sizing: border-box;
            }
            body{
                font-family: 'Ubuntu', sans-serif;
            }
            nav{
                background: black;
                height: 80px;
                width: 100%;
            }
            label.logo{
                color: white;
                font-size: 35px;
                line-height: 80px;
                padding: 0 100px;
                font-weight: bold;
            }
            nav ul{
                float: right;
                margin-right: 20px;
            }
            nav ul li{
                display: inline-block;
                line-height: 80px;
                margin: 0 5px;
            }
            nav ul li a{
                color: white;
                font-size: 17px;
                padding: 7px 13px;
                border-radius: 3px;
                text-transform: uppercase;

            }
            a.active,a.hover{
                background: #1b9bff;
                transition: .5s;
            }
            table {
              font-family: 'Ubuntu', sans-serif;
              border-collapse: collapse;
              width: 60%;
            }

            td, th {
              border: 3px solid #dddddd;
              text-align: left;
              padding: 8px;
            }

            tr:nth-child(even) {
              background-color: #dddddd;
            }

            .button {
              background-color: #4CAF50; /* Green */
              border: none;
              color: white;
              padding: 10px 32px;
              text-align: center;
              text-decoration: none;
              display: inline-block;
              font-size: 16px;
              margin: 4px 2px;
              transition-duration: 0.4s;
              cursor: pointer;
            }

            .button1 {
              background-color: white;
              color: black;
              border: 2px solid #4CAF50;
            }

            .button1:hover {
              background-color: #4CAF50;
              color: white;
            }

            .button3 {
              background-color: white;
              color: black;
              border: 2px solid #f44336;
            }

            .button3:hover {
              background-color: #f44336;
              color: white;
            }
            .button5 {
              background-color: white;
              color: black;
              border: 2px solid #ffffff;
            }

            .button5:hover {
              background-color: #ffffff;
              color: white;
            }
        

        </style>


        <title>
            Subjects
        </title>
    </head>
    <body>
        {% block body %}
        {% endblock %}

    </body>
</html>

inception/subjects/templates/subjects/subject.html
{% extends "subjects/layout.html" %}


{% block body %}
    <nav>

    <label class="logo"><a href="{% url 'subjects:index' %}">Subject</a></label>
    <ul>
    <li><a class="active" href="https://ide-6bd6267e6ac441ff8a573303d9997bd7-8080.cs50.ws/">HOME</a></li>

    <li><a href="{% url 'subjects:Course' %}">course</a></li>
    </ul>
    </nav><br>
    <center><h2>SUBJECT  {{ subject.subject_code }}</h2></center>
    <br><br>
    <center><TABLE>
            <thead>
            <TR>
                <TH> Subject ID</TH>
                <TH> Subject Name</TH>
                <TH> Semester </TH>
                <th> Year </th>
                <th> Seat </th>
            </TR>
            </thead>
                <TD>{{ subject.subject_code }}</TD>
                <TD>{{ subject.subject_name }}</TD>
                <TD>{{ subject.semester }}</TD>
                <TD>{{ subject.year  }}</TD>
                <TD>{{ subject.seat }}</TD>

                </TABLE></center>

    <br><br><br>

    <center>

    <a href ="{% url 'subjects:enroll' subject.id %}">
        {% if subject.seat is 0 %}
            <button class="button button1" onclick="alert('ลงทะเบียนไม่สำเร็จ')">enroll</button>
        {% elif user  in subject.studentInClass.all %}
        {% else %}
            <button class="button button1" onclick="alert('ลงทะเบียนสำเร็จ')">enroll </button>
        {% endif %}
    </a>

    <a href ="{% url 'subjects:drop' subject.id %}">
        {% if subject.status is full %}
    <button class="button button3" onclick="alert('ถอนวิชาไม่สำเร็จ')">withdraw</button>
        {% elif user  not in subject.studentInClass.all %}
        {% else %}
    <button class="button button3" onclick="alert('ถอนวิชาสำเร็จ')">withdraw</button>
        {% endif %}
    </a>

    <a href="{% url 'subjects:index' %}">
    <button class="button button5" >back</button>
    </a> </center>

{% endblock %}

inception/templates/base.html
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
      @import url(https://fonts.googleapis.com/css?family=Oswald:400);
      @import url('https://fonts.googleapis.com/css2?family=Ubuntu&display=swap');
      body{
        margin: 0;
        padding: 0;
        font-family: 'Ubuntu', sans-serif;
        background:  black;
          }
      .box{
        width: 600px;
        padding: 50px;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: #191919;
        text-align: center;
      }
      .box h1 {
        color: white;
        text-transform: uppercase;
        font-weight: 500;
        font-weight: bold;
      }
      .box h3 {
        color: white;
        text-transform: lowercase;
        font-weight: 200;
      }
      .box input[type="text"],.box input[type="password"]{
        border:0;
        background: none;
        display: block;
        margin: 20px auto;
        text-align: center;
        border: 2px solid #3498db;
        padding: 14px 4px;
        width: 350px;
        outline: none;
        color: white;
        border-radius: 24px;
        transition: 0.25s;
      }
      .box input[type="text"]:focus,.box input[type="password"]:focus{
        width: 380px;
        border-color: #2ecc71;
      }
      .box input[type="submit"]{
        border:0;
        background: none;
        display: block;
        margin: 20px auto;
        text-align: center;
        border: 2px solid #3498db;
        padding: 14px 60px;
        outline: none;
        color: white;
        border-radius: 24px;
        transition: 0.25s;
        cursor: pointer;
      }
      .box input[type="submit"]:hover{
        background: #2ecc71;
      }
      h1 {
        color: #95a5a6;
        font-weight: 500;
        font-weight: bold;
      }
      h2 {
        color: white;
        font-weight: 200;
        font-weight: bold;
      }

     li, a, button{
       font-weight: 500;
       font-size: 16px;
       color: #edf0f1;
       text-decoration: none;
     }

      h4 {
        color: #bdc3c7;
        font-weight: 200;

      }
      * {
        box-sizing: border-box;
        margin:0;
        padding: 0;
      }
      header{
        display: flex;
        justify-content: flex-end;
        align-items: center;
        padding: 0px 10%;
      }
      .nav_links{
        list-style: none;
      }
      .nav_links li{
        display: inline-block;
        padding: 0px 20px;
      }
      .nav_links li a{
        transition: all 0.3s ease 0s;
      }
      .nav_links li a:hover{
        color: #0088a9;
      }
      button {
        margin-left: 20px;
        padding: 12px 25px;
        background-color:#ff0047;
        border: none
        border-radius: 50px;
        cursor: pointer;
        transition: all 0.3s ease 0s;
      }
      button:hover {
        background-color: rgba(0,136,169,0);
      }
     .logo{
       margin-right: auto;
       color: black;
     }
     nav{
                background: white;
                height: 100px;
                width: 100%;
            }
      h3 {
        color: white;
        font-weight: 180;
        font-weight: bold;
      }



    </style>

  <center><meta charset="utf-8">
  <title>{% block title %}Log in{% endblock %}</title></center>
</head>
<body>
  <main><center>
    {% block content %}
    {% endblock %}</center>
  </main>
</body>
</html>

inception/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<nav>
<header>
<h1 class="logo">Welcome {{ user.username }}</h1>

 <br>

    {% if user.username == "admin" %}
        <br><br><br>
        <a class="logout" href="{% url 'logout' %}"><button>Logout</button></a>

     {% else %}

     <ul class="nav_links">
         <br>

        </ul>
        <a class="logout" href="{% url 'logout' %}"><button>Logout</button></a>

     {% endif %}
     </header>
     </nav>
     <br><br><br><br>
     <h2> Please select your option !</h2>

     <h2> User : {{user}}</h2>

     <h2> Email : {{user.email}}</h2>
    {% if user.username != "admin" %}
    <br>
    <div class="w3-center">
        <br><br>
            <div class="w3-bar">
                <button class="w3-button w3-round-xlarge"  ><a href="{% url 'subjects:index' %}">Subjects</a></button>
                </div>
                </div>
                <div class="w3-center">
        <br><br>
            <div class="w3-bar">
                <button class="w3-button w3-round-xlarge"  ><a href="{% url 'subjects:Course' %}">Course</a></button>
                </div>
                </div>
    {% endif %}
    {% else %}
      <form method="post" action="{% url 'login' %}" class="box">
          {% csrf_token %}
      <p><h2>You are not logged in</h2></p>
      <input type="submit" name="" value="Login">
    {% endif %}
    <!-- <ul class="nav_links">

        <!--<li><a href="https://ide-6bd6267e6ac441ff8a573303d9997bd7-8080.cs50.ws/admin/" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Edit data</a></li>
        <!-- <div class="navigation">
	    <a class="button" href="{% url 'logout' %}">
         <div class="logout">LOGOUT</div>
	    </a>
        </div> -->
        <br><br>
        {% if user.username == "admin" %}
        <div class="w3-center">
            <div class="w3-bar">
                <button class="w3-button w3-round-xlarge" ><a href="https://ide-6bd6267e6ac441ff8a573303d9997bd7-8080.cs50.ws/admin/">Edit data</a></button>
                </div>
                </div>
        </ul>

        {% endif %}


    {% endblock %}


<!-- <li><a href="https://ide-6bd6267e6ac441ff8a573303d9997bd7-8080.cs50.ws/admin/" class="round green">Login<span class="round">That is, if you are an admin.</span></a></li>
  <li><a href="https://ide-6bd6267e6ac441ff8a573303d9997bd7-8080.cs50.ws/admin/" class="round red">Sign Up<span -->

 